<?php

/**
 *	Class to generate a password according to personal rules
 */
class modGeneratePassPerso extends \ModeleGenPassword
{
    /**
     * @var string ID
     */
    public $id;
    public $picto = 'fa-shield-alt';
    /**
     * @var string
     */
    public $NbMaj;
    /**
     * @var string
     */
    public $NbNum;
    /**
     * @var string
     */
    public $NbSpe;
    /**
     * @var string
     */
    public $NbRepeat;
    /**
     * Flag to 1 if we must clean ambiguous characters for the autogeneration of password (List of ambiguous char is in $this->Ambi)
     *
     * @var integer
     */
    public $WithoutAmbi = 0;
    /**
     * @var string
     */
    public $Maj;
    /**
     * @var string
     */
    public $Min;
    /**
     * @var string
     */
    public $Nb;
    /**
     * @var string
     */
    public $Spe;
    /**
     * @var array<int,string>
     */
    public $Ambi;
    /**
     * @var string
     */
    public $All;
    /**
     *	Constructor
     *
     *  @param		DoliDB		$db			Database handler
     *	@param		Conf		$conf		Handler de conf
     *	@param		Translate	$langs		Handler de langue
     *	@param		User		$user		Handler du user connected
     */
    public function __construct($db, $conf, $langs, $user)
    {
    }
    /**
     *	Init the property ->All and clean ->Maj, ->Min, ->Nb and ->Spe with list of valid chars
     *
     *  @return		void
     */
    private function initAll()
    {
    }
    /**
     *	Return description of module
     *
     *  @return     string      Description of text
     */
    public function getDescription()
    {
    }
    /**
     * 	Return an example of password generated by this module
     *
     *  @return     string      Example of password
     */
    public function getExample()
    {
    }
    /**
     *  Build new password
     *
     *  @return     string      Return a new generated password
     *
     *  @phan-suppress PhanPossiblyInfiniteRecursionSameParams
     */
    public function getNewGeneratedPassword()
    {
    }
    /**
     *  Validate a password.
     * 	This function is called by User->setPassword() and internally to validate that the password matches the constraints.
     *
     *  @param      string  $password   Password to check
     *  @return     int					0 if KO, >0 if OK
     */
    public function validatePassword($password)
    {
    }
    /**
     *  Check the consecutive iterations of the same character.
     *
     *  @param		string	$password	Password to check
     *  @return     bool				False if the number doesn't match the maximum consecutive value allowed.
     */
    public function consecutiveIterationSameCharacter($password)
    {
    }
}