<?php

$action = \GETPOST('action', 'aZ09');
// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : 'holidaylist';
// To manage different context of search
$mode = \GETPOST('mode', 'alpha');
// for switch mode view result
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$id = \GETPOSTINT('id');
$childids = $user->getAllChildIds(1);
$diroutputmassaction = $conf->holiday->dir_output . '/temp/massgeneration/' . $user->id;
// Load variable for pagination
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
// If $page is not defined, or '' or -1
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
$search_all = \trim(\GETPOST('search_all', 'alphanohtml'));
$search_ref = \GETPOST('search_ref', 'alphanohtml');
$search_day_create = \GETPOST('search_day_create', 'int');
$search_month_create = \GETPOST('search_month_create', 'int');
$search_year_create = \GETPOST('search_year_create', 'int');
$search_day_start = \GETPOST('search_day_start', 'int');
$search_month_start = \GETPOST('search_month_start', 'int');
$search_year_start = \GETPOST('search_year_start', 'int');
$search_day_end = \GETPOST('search_day_end', 'int');
$search_month_end = \GETPOST('search_month_end', 'int');
$search_year_end = \GETPOST('search_year_end', 'int');
$search_employee = \GETPOST('search_employee', 'intcomma');
$search_valideur = \GETPOST('search_valideur', 'intcomma');
$search_status = \GETPOST('search_status', 'intcomma');
$search_type = \GETPOST('search_type', 'intcomma');
// Initialize a technical objects
$object = new \Holiday($db);
$extrafields = new \ExtraFields($db);
$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');
// List of fields to search into when doing a "search in all"
$fieldstosearchall = array('cp.ref' => 'Ref', 'cp.description' => 'Description', 'uu.lastname' => 'EmployeeLastname', 'uu.firstname' => 'EmployeeFirstname', 'uu.login' => 'Login');
$arrayfields = array('cp.ref' => array('label' => $langs->trans("Ref"), 'checked' => '1'), 'cp.fk_user' => array('label' => $langs->trans("Employee"), 'checked' => '1', 'position' => 20), 'cp.fk_validator' => array('label' => $langs->trans("ValidatorCP"), 'checked' => '1', 'position' => 30), 'cp.fk_type' => array('label' => $langs->trans("Type"), 'checked' => '1', 'position' => 35), 'duration' => array('label' => $langs->trans("NbUseDaysCPShort"), 'checked' => '1', 'position' => 38), 'cp.date_debut' => array('label' => $langs->trans("DateStart"), 'checked' => '1', 'position' => 40), 'cp.date_fin' => array('label' => $langs->trans("DateEnd"), 'checked' => '1', 'position' => 42), 'cp.date_valid' => array('label' => $langs->trans("DateValidation"), 'checked' => '1', 'position' => 60), 'cp.date_approval' => array('label' => $langs->trans("DateApprove"), 'checked' => '1', 'position' => 70), 'cp.date_create' => array('label' => $langs->trans("DateCreation"), 'checked' => '0', 'position' => 500), 'cp.tms' => array('label' => $langs->trans("DateModificationShort"), 'checked' => '0', 'position' => 501), 'cp.statut' => array('label' => $langs->trans("Status"), 'checked' => '1', 'position' => 1000));
// Security check
$socid = 0;
$permissiontoread = $user->hasRight('holiday', 'read');
$permissiontodelete = $user->hasRight('holiday', 'delete');
$permissiontoapprove = $user->hasRight('holiday', 'approve');
$result = \restrictedArea($user, 'holiday', '', '');
$canread = 0;
$parameters = array('socid' => $socid, 'arrayfields' => &$arrayfields);
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Mass actions
$objectclass = 'Holiday';
$objectlabel = 'Holiday';
$uploaddir = $conf->holiday->dir_output;
/*
 * View
 */
$form = new \Form($db);
$formother = new \FormOther($db);
$formfile = new \FormFile($db);
$fuser = new \User($db);
$holidaystatic = new \Holiday($db);
// Update sold
$result = $object->updateBalance();
$title = $langs->trans('Holidays');
$help_url = 'EN:Module_Holiday';
$max_year = 5;
$min_year = 10;
// Get current user id
$user_id = $user->id;
// Récupération des congés payés de l'utilisateur ou de tous les users de sa hierarchy
// Load array $object->holiday
$sql = "SELECT";
// Add fields from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListSelect', $parameters);
$sql = \preg_replace('/,\\s*$/', '', $sql);
$sqlfields = $sql;
// Add where from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListWhere', $parameters, $object, $action);
// Count total nb of records
$nbtotalofrecords = '';
/* The fast and low memory method to get and count full list converts the sql into a sql count */
$sqlforcount = \preg_replace('/^' . \preg_quote($sqlfields, '/') . '/', 'SELECT COUNT(*) as nbtotalofrecords', $sql);
$sqlforcount = \preg_replace('/GROUP BY .*$/', '', $sqlforcount);
$resql = $db->query($sqlforcount);
//print $sql;
$resql = $db->query($sql);
$num = $db->num_rows($resql);
$arrayofselected = \is_array($toselect) ? $toselect : array();
$param = '';
// List of mass actions available
$arrayofmassactions = array();
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);
// For user tab
$title = $langs->trans("User");
$linkback = '<a href="' . \DOL_URL_ROOT . '/user/list.php?restore_lastsearch_values=1">' . $langs->trans("BackToList") . '</a>';
$head = \user_prepare_head($fuser);
$cancreate = 0;
$topicmail = "Information";
$modelmail = "leaverequest";
$objecttmp = new \Holiday($db);
$trackid = 'leav' . $object->id;
$moreforfilter = '';
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object, $action);
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
$htmlofselectarray = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, \getDolGlobalString('MAIN_CHECKBOX_LEFT_COLUMN'));
// This also change content of $arrayfields with user setup
$selectedfields = $mode != 'kanban' ? $htmlofselectarray : '';
$include = '';
$morefilter = '';
// User
$disabled = 0;
// Fields from hook
$parameters = array('arrayfields' => $arrayfields);
$reshook = $hookmanager->executeHooks('printFieldListOption', $parameters, $object, $action);
$totalarray = array();
// Hook fields
$parameters = array('arrayfields' => $arrayfields, 'param' => $param, 'sortfield' => $sortfield, 'sortorder' => $sortorder, 'totalarray' => &$totalarray);
$reshook = $hookmanager->executeHooks('printFieldListTitle', $parameters, $object, $action);
$listhalfday = array('morning' => $langs->trans("Morning"), "afternoon" => $langs->trans("Afternoon"));
$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $object, $action);
/**
 * Show balance of user
 *
 * @param 	Holiday	$holiday	Object $holiday
 * @param	int		$user_id	User id
 * @return	string				Html code with balance
 */
function showMyBalance($holiday, $user_id)
{
}