<?php

$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$mode = \GETPOST('mode', 'alpha');
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : 'myobjectlist';
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$search_id = \GETPOST('search_id', 'alphanohtml');
$search_month = \GETPOSTINT('search_month');
$search_year = \GETPOSTINT('search_year');
$search_employee = \GETPOST('search_employee', "intcomma");
$search_validator = \GETPOST('search_validator', "intcomma");
$search_description = \GETPOST('search_description', 'alphanohtml');
$search_type = \GETPOST('search_type', "intcomma");
$search_prev_solde = \GETPOST('search_prev_solde', 'alphanohtml');
$search_new_solde = \GETPOST('search_new_solde', 'alphanohtml');
// Load variable for pagination
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
// If $page is not defined, or '' or -1 or if we click on clear filters or if we select empty mass action
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
// Initialize a technical objects
$object = new \Holiday($db);
$extrafields = new \ExtraFields($db);
// Note that conf->hooks_modules contains array
$arrayfields = array();
$arrayofmassactions = array();
$parameters = array();
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Definition of fields for lists
$arrayfields = array('cpl.rowid' => array('label' => "ID", 'checked' => '1'), 'cpl.date_action' => array('label' => "Date", 'checked' => '1'), 'cpl.fk_user_action' => array('label' => "ActionByCP", 'checked' => '1'), 'cpl.fk_user_update' => array('label' => "UserUpdateCP", 'checked' => '1'), 'cpl.type_action' => array('label' => "Description", 'checked' => '1'), 'cpl.fk_type' => array('label' => "Type", 'checked' => '1'), 'cpl.prev_solde' => array('label' => "PrevSoldeCP", 'checked' => '1'), 'variation' => array('label' => "Variation", 'checked' => '1'), 'cpl.new_solde' => array('label' => "NewSoldeCP", 'checked' => '1'));
/*
 * View
 */
$form = new \Form($db);
$formother = new \FormOther($db);
$holidaylogstatic = new \stdClass();
$alltypeleaves = $object->getTypes(1, -1);
// To have labels
$title = $langs->trans('CPTitreMenu');
$help_url = 'EN:Module_Holiday';
$sqlwhere = '';
$sqlorder = $db->order($sortfield, $sortorder);
// Recent changes are more important than old changes
$log_holiday = $object->fetchLog($sqlorder, $sqlwhere);
// Load $object->logs
// Count total nb of records
$nbtotalofrecords = '';
//TODO: $result = $db->query($sql);
//TODO: $nbtotalofrecords = $db->num_rows($result);
$nbtotalofrecords = \is_array($object->logs) ? \count($object->logs) : 0;
// TODO: $num = $db->num_rows($resql);
$num = \is_array($object->logs) ? \count($object->logs) : 0;
$param = '';
$newcardbutton = \dolGetButtonTitle($langs->trans('MenuAddCP'), '', 'fa fa-plus-circle', \DOL_URL_ROOT . '/holiday/card.php?action=create', '', $user->hasRight('holiday', 'write'));
$lastUpdate = $object->getConfCP('lastUpdate');
$moreforfilter = '';
$morefilter = '';
$disabled = 0;
$include = '';
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
$htmlofselectarray = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, \getDolGlobalString('MAIN_CHECKBOX_LEFT_COLUMN'));
// This also change content of $arrayfields with user setup
$selectedfields = $mode != 'kanban' ? $htmlofselectarray : '';
$j = 0;
$i = 0;