<?php

// Get Parameters
$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : \str_replace('_', '', \basename(\dirname(__FILE__)) . \basename(__FILE__, '.php'));
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$mode = \GETPOST('mode', 'aZ');
$id = \GETPOSTINT('id');
$conf_or_booth_id = \GETPOSTINT('conforboothid');
$withproject = \GETPOSTINT('withproject');
$fk_project = \GETPOSTINT('fk_project') ? \GETPOSTINT('fk_project') : \GETPOSTINT('projectid');
$projectid = $fk_project;
$projectref = \GETPOST('projectref');
$withProjectUrl = '';
// Load variable for pagination
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
// Initialize a technical objects
$object = new \ConferenceOrBoothAttendee($db);
$project = new \Project($db);
$projectstatic = new \Project($db);
$extrafields = new \ExtraFields($db);
$diroutputmassaction = $conf->eventorganization->dir_output . '/temp/massgeneration/' . $user->id;
//$extrafields->fetch_name_optionals_label($object->table_element_line);
$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');
// Initialize array of search criteria
$search_all = \GETPOST('search_all', 'alphanohtml');
$search = array();
// List of fields to search into when doing a "search in all"
$fieldstosearchall = array();
// Definition of array of fields for columns
$arrayfields = array();
$arrayfields = \dol_sort_array($arrayfields, 'position');
// Permissions
$permissiontoread = $user->hasRight('project', 'read');
$permissiontoadd = $user->hasRight('project', 'write');
$permissiontodelete = $user->hasRight('project', 'delete');
$result = \restrictedArea($user, 'project');
//If "set" fields keys is in projects fields
$project_attr = \preg_replace('/^set/', '', $action);
$parameters = array();
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Mass actions
$objectclass = 'ConferenceOrBoothAttendee';
$objectlabel = 'ConferenceOrBoothAttendee';
$uploaddir = $conf->eventorganization->dir_output;
/*
 * View
 */
$form = new \Form($db);
$now = \dol_now();
$help_url = "EN:Module_Event_Organization";
$morejs = array();
$morecss = array();
$confOrBooth = new \ConferenceOrBooth($db);
$result = $confOrBooth->fetch($conf_or_booth_id);
$result = $projectstatic->fetch($fk_project);
// Build and execute select
// --------------------------------------------------------------------
$sql = 'SELECT ';
// Add fields from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListSelect', $parameters, $object, $action);
$sql = \preg_replace('/,\\s*$/', '', $sql);
//$sql .= ", COUNT(rc.rowid) as anotherfield";
$sqlfields = $sql;
// Add table from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListFrom', $parameters, $object, $action);
// Add where from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListWhere', $parameters, $object, $action);
// Count total nb of records
$nbtotalofrecords = '';
/* The fast and low memory method to get and count full list converts the sql into a sql count */
$sqlforcount = \preg_replace('/^' . \preg_quote($sqlfields, '/') . '/', 'SELECT COUNT(*) as nbtotalofrecords', $sql);
$sqlforcount = \preg_replace('/GROUP BY .*$/', '', $sqlforcount);
$resql = $db->query($sqlforcount);
$resql = $db->query($sql);
$num = $db->num_rows($resql);
$withProjectUrl = '';
$arrayofselected = \is_array($toselect) ? $toselect : array();
$param = '';
// Add $param from hooks
$parameters = array('param' => &$param);
$reshook = $hookmanager->executeHooks('printFieldListSearchParam', $parameters, $object, $action);
// List of mass actions available
$arrayofmassactions = array(
    //'validate'=>img_picto('', 'check', 'class="pictofixedwidth"').$langs->trans("Validate"),
    //'generate_doc'=>img_picto('', 'pdf', 'class="pictofixedwidth"').$langs->trans("ReGeneratePDF"),
    //'builddoc'=>img_picto('', 'pdf', 'class="pictofixedwidth"').$langs->trans("PDFMerge"),
    'presend' => \img_picto('', 'email', 'class="pictofixedwidth"') . $langs->trans("SendByMail"),
);
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);
$params = array('morecss' => 'reposition');
$urlnew = \DOL_URL_ROOT . '/eventorganization/conferenceorboothattendee_card.php?action=create' . (!empty($confOrBooth->id) ? '&conforboothid=' . $confOrBooth->id : '') . (!empty($projectstatic->id) ? '&fk_project=' . $projectstatic->id : '') . $withProjectUrl . '&backtopage=' . \urlencode($_SERVER['PHP_SELF'] . '?projectid=' . $projectstatic->id . (empty($confOrBooth->id) ? '' : '&conforboothid=' . $confOrBooth->id) . $withProjectUrl);
$newcardbutton = '';
// Add code for pre mass action (confirmation or email presend form)
$topicmail = $projectstatic->title;
$modelmail = "conferenceorbooth";
$objecttmp = new \ConferenceOrBoothAttendee($db);
$trackid = 'conferenceorbooth_' . $object->id;
$withmaindocfilemail = 0;
$moreforfilter = '';
/*$moreforfilter.='<div class="divsearchfield">';
$moreforfilter.= $langs->trans('MyFilter') . ': <input type="text" name="search_myfield" value="'.dol_escape_htmltag($search_myfield).'">';
$moreforfilter.= '</div>';*/
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object, $action);
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
$htmlofselectarray = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, \getDolGlobalString('MAIN_CHECKBOX_LEFT_COLUMN'));
// This also change content of $arrayfields with user setup
$selectedfields = $mode != 'kanban' ? $htmlofselectarray : '';
// Fields from hook
$parameters = array('arrayfields' => $arrayfields);
$reshook = $hookmanager->executeHooks('printFieldListOption', $parameters, $object, $action);
$totalarray = array();
// Hook fields
$parameters = array('arrayfields' => $arrayfields, 'param' => $param, 'sortfield' => $sortfield, 'sortorder' => $sortorder, 'totalarray' => &$totalarray);
$reshook = $hookmanager->executeHooks('printFieldListTitle', $parameters, $object, $action);
// Detect if we need a fetch on each output line
$needToFetchEachLine = 0;
// Loop on record
// --------------------------------------------------------------------
$i = 0;
$savnbfield = $totalarray['nbfield'];
$totalarray = array();
$imaxinloop = $limit ? \min($num, $limit) : $num;
$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $object, $action);
$hidegeneratedfilelistifempty = 1;
$formfile = new \FormFile($db);
// Show list of available documents
$urlsource = $_SERVER['PHP_SELF'] . '?sortfield=' . $sortfield . '&sortorder=' . $sortorder;
$filedir = $diroutputmassaction;
$genallowed = $permissiontoread;
$delallowed = $permissiontoadd;