<?php

// autoload_real.php @generated by Composer
class ComposerAutoloaderInit60b9ac98a8448ede6c445b0fd4bd31e0
{
    private static $loader;
    public static function loadClassLoader($class)
    {
    }
    public static function getLoader()
    {
    }
}
function composerRequire60b9ac98a8448ede6c445b0fd4bd31e0($fileIdentifier, $file)
{
}