<?php

/**
 * Generate a self-verifiable state token for the OIDC authorization request.
 *
 * Uses HMAC with the instance unique ID as secret so the state can be verified
 * without depending on the original session. This is necessary because browsers
 * with SameSite=Lax cookies do not send the session cookie on cross-site redirects
 * from the OIDC provider, causing a new session to be created on the callback.
 *
 * @return  string				State token (format: nonce.signature)
 */
function openid_connect_get_state()
{
}
/**
 * Verify an OIDC state token.
 *
 * Checks that the state was generated by this Dolibarr instance by recomputing
 * the HMAC signature from the nonce and comparing it to the provided signature.
 *
 * @param   string  $state		The state token to verify (format: nonce.signature)
 * @return  bool				True if valid, false otherwise
 */
function openid_connect_verify_state($state)
{
}
/**
 * Return the OIDC callback redirect URL
 *
 * @return  string				Redirect URL
 */
function openid_connect_get_redirect_url()
{
}
/**
 * Return the OIDC authorization URL
 *
 * @return  string				Authorization URL
 */
function openid_connect_get_url()
{
}
/**
 * Create a Dolibarr user from OIDC userinfo claims.
 *
 * The login is sanitized to remove characters not allowed by Dolibarr (e.g. @ from emails).
 * If the OIDC userinfo contains a preferred_username claim without bad characters, it is used instead.
 *
 * @param  DoliDB  $db              Database handler
 * @param  stdClass $userinfo       Decoded OIDC userinfo JSON (claims from json_decode)
 * @param  string  $login           Login value extracted from the configured claim
 * @param  int     $entity          Entity (multicompany) ID
 * @return string|int               Sanitized login string on success, negative int on failure
 * @see check_user_password_openid_connect()
 */
function openid_connect_create_user($db, $userinfo, $login, $entity)
{
}