<?php

$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'create'/'add', 'edit'/'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : \str_replace('_', '', \basename(\dirname(__FILE__)) . \basename(__FILE__, '.php'));
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$mode = \GETPOST('mode', 'aZ');
// The output mode ('list', 'kanban', 'hierarchy', 'calendar', ...)
$statut = \GETPOSTISSET("statut") ? \GETPOST("statut", "alpha") : 1;
$search_ref = \GETPOST('search_ref', 'alpha');
$search_type = \GETPOSTINT('search_type');
$search_lastname = \GETPOST('search_lastname', 'alpha');
$search_firstname = \GETPOST('search_firstname', 'alpha');
$search_login = \GETPOST('search_login', 'alpha');
$search_note = \GETPOST('search_note', 'alpha');
$search_account = \GETPOST('search_account', 'alpha');
$search_amount = \GETPOST('search_amount', 'alpha');
$search_all = \trim(\GETPOST('search_all', 'alphanohtml'));
$date_select = \GETPOST("date_select", 'alpha');
// Load variable for pagination
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
// Initialize a technical objects
$object = new \Subscription($db);
$extrafields = new \ExtraFields($db);
$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');
// List of fields to search into when doing a "search in all"
$fieldstosearchall = array('c.rowid' => 'Ref', 'c.note' => "Label");
$arrayfields = array(
    'd.ref' => array('label' => "Ref", 'checked' => '1'),
    'd.fk_type' => array('label' => "Type", 'checked' => '1'),
    'd.lastname' => array('label' => "Lastname", 'checked' => '1'),
    'd.firstname' => array('label' => "Firstname", 'checked' => '1'),
    'd.login' => array('label' => "Login", 'checked' => '1'),
    'c.note' => array('label' => "Label", 'checked' => '1'),
    'd.bank' => array('label' => "BankAccount", 'checked' => '1', 'enabled' => (string) (int) \isModEnabled('bank')),
    /*'d.note_public'=>array('label'=>"NotePublic", 'checked'=>0),
    	 'd.note_private'=>array('label'=>"NotePrivate", 'checked'=>0),*/
    'c.dateadh' => array('label' => "DateSubscription", 'checked' => '1', 'position' => 100),
    'c.datef' => array('label' => "EndSubscription", 'checked' => '1', 'position' => 101),
    'd.amount' => array('label' => "Amount", 'checked' => '1', 'position' => 102),
    'c.datec' => array('label' => "DateCreation", 'checked' => '0', 'position' => 500),
    'c.tms' => array('label' => "DateModificationShort", 'checked' => '0', 'position' => 500),
);
$permissiontodelete = $user->hasRight('adherent', 'cotisation', 'creer');
$parameters = array('socid' => isset($socid) ? $socid : \null);
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Mass actions
$objectclass = 'Subscription';
$objectlabel = 'Subscription';
$uploaddir = $conf->member->dir_output;
/*
 * View
 */
$form = new \Form($db);
$subscription = new \Subscription($db);
$adherent = new \Adherent($db);
$adht = new \AdherentType($db);
$accountstatic = new \Account($db);
$now = \dol_now();
// List of subscriptions
$sql = "SELECT d.rowid, d.login, d.firstname, d.lastname, d.societe, d.photo, d.statut as status,";
// Add fields from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListSelect', $parameters, $object, $action);
$sql = \preg_replace('/,\\s*$/', '', $sql);
$sqlfields = $sql;
// Add where from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListWhere', $parameters, $object, $action);
// Count total nb of records
$nbtotalofrecords = '';
/* The fast and low memory method to get and count full list converts the sql into a sql count */
$sqlforcount = \preg_replace('/^' . \preg_quote($sqlfields, '/') . '/', 'SELECT COUNT(*) as nbtotalofrecords', $sql);
$sqlforcount = \preg_replace('/GROUP BY .*$/', '', $sqlforcount);
$resql = $db->query($sqlforcount);
$resql = $db->query($sql);
$num = $db->num_rows($resql);
// Output page
// --------------------------------------------------------------------
$title = $langs->trans("Subscriptions");
$help_url = 'EN:Module_Foundations|FR:Module_Adh&eacute;rents|ES:M&oacute;dulo_Miembros|DE:Modul_Mitglieder';
$arrayofselected = \is_array($toselect) ? $toselect : array();
$param = '';
// Add $param from hooks
$parameters = array('param' => &$param);
$reshook = $hookmanager->executeHooks('printFieldListSearchParam', $parameters, $object, $action);
// List of mass actions available
$arrayofmassactions = array();
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);
$newcardbutton = '';
$topicmail = "Information";
$modelmail = "subscription";
$objecttmp = new \Subscription($db);
$trackid = 'sub' . $object->id;
$moreforfilter = '';
/*$moreforfilter.='<div class="divsearchfield">';
 $moreforfilter.= $langs->trans('MyFilter') . ': <input type="text" name="search_myfield" value="'.dol_escape_htmltag($search_myfield).'">';
 $moreforfilter.= '</div>';*/
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object, $action);
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
$htmlofselectarray = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, \getDolGlobalString('MAIN_CHECKBOX_LEFT_COLUMN'));
// This also change content of $arrayfields with user setup
$selectedfields = $mode != 'kanban' ? $htmlofselectarray : '';
// Fields from hook
$parameters = array('arrayfields' => $arrayfields);
$reshook = $hookmanager->executeHooks('printFieldListOption', $parameters, $object, $action);
$totalarray = array();
// Hook fields
$parameters = array('arrayfields' => $arrayfields, 'param' => $param, 'sortfield' => $sortfield, 'sortorder' => $sortorder, 'totalarray' => &$totalarray);
$reshook = $hookmanager->executeHooks('printFieldListTitle', $parameters, $object, $action);
// Loop on record
// --------------------------------------------------------------------
$i = 0;
$savnbfield = $totalarray['nbfield'];
$totalarray = array();
$imaxinloop = $limit ? \min($num, $limit) : $num;
$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $object, $action);