<?php

//
// File generated by Dolibarr installer 18.0.8 on 23 Déc. 2025
//
// Take a look at conf.php.example file for an example of conf.php file
// and explanations for all possibles parameters.
//
$dolibarr_main_url_root = 'http://localhost:8080';
$dolibarr_main_document_root = __DIR__ . '/htdocs';
$dolibarr_main_url_root_alt = '/custom';
$dolibarr_main_document_root_alt = __DIR__ . '/htdocs/custom';
$dolibarr_main_data_root = __DIR__ . '/documents';
$dolibarr_main_db_host = 'localhost';
$dolibarr_main_db_port = '';
$dolibarr_main_db_name = 'dolibarr';
$dolibarr_main_db_prefix = 'llx_';
$dolibarr_main_db_user = 'admin';
$dolibarr_main_db_pass = 'admin';
$dolibarr_main_db_type = 'sqlite3';
$dolibarr_main_db_character_set = 'UTF-8';
$dolibarr_main_db_collation = 'UTF-8';
// Authentication settings
$dolibarr_main_authentication = 'dolibarr';
//$dolibarr_main_demo='autologin,autopass';
// Security settings
$dolibarr_main_prod = '0';
$dolibarr_main_force_https = '0';
$dolibarr_main_restrict_os_commands = 'mysqldump, mysql, pg_dump, pgrestore, clamdscan, clamscan.exe';
$dolibarr_nocsrfcheck = '0';
$dolibarr_main_instance_unique_id = '64bb9bfca3ceff3db04e0b5677e34492';
$dolibarr_mailing_limit_sendbyweb = '0';
$dolibarr_mailing_limit_sendbycli = '0';
//$dolibarr_lib_FPDF_PATH='';
//$dolibarr_lib_TCPDF_PATH='';
//$dolibarr_lib_FPDI_PATH='';
//$dolibarr_lib_TCPDI_PATH='';
//$dolibarr_lib_GEOIP_PATH='';
//$dolibarr_lib_NUSOAP_PATH='';
//$dolibarr_lib_ODTPHP_PATH='';
//$dolibarr_lib_ODTPHP_PATHTOPCLZIP='';
//$dolibarr_js_CKEDITOR='';
//$dolibarr_js_JQUERY='';
//$dolibarr_js_JQUERY_UI='';
//$dolibarr_font_DOL_DEFAULT_TTF='';
//$dolibarr_font_DOL_DEFAULT_TTF_BOLD='';
$dolibarr_main_distrib = 'standard';