<?php

$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : \str_replace('_', '', \basename(\dirname(__FILE__)) . \basename(__FILE__, '.php'));
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$mode = \GETPOST("mode", 'aZ');
// Security check (for external users)
$socid = 0;
// Load variable for pagination
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
// Initialize a technical object to manage hooks of page. Note that conf->hooks_modules contains an array of hook context
$object = new \User($db);
$extrafields = new \ExtraFields($db);
$diroutputmassaction = $conf->user->dir_output . '/temp/massgeneration/' . $user->id;
$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');
// Initialize array of search criteria
$search_all = \trim(\GETPOST('search_all', 'alphanohtml'));
$search = array();
$userstatic = new \User($db);
$companystatic = new \Societe($db);
$form = new \Form($db);
// List of fields to search into when doing a "search in all"
$fieldstosearchall = array('u.login' => "Login", 'u.lastname' => "Lastname", 'u.firstname' => "Firstname", 'u.accountancy_code' => "AccountancyCode", 'u.office_phone' => "PhonePro", 'u.user_mobile' => "PhoneMobile", 'u.email' => "EMail", 'co.label' => "Country", 'u.note_public' => "NotePublic", 'u.note_private' => "NotePrivate");
$permissiontoreadhr = $user->hasRight('hrm', 'read_personal_information', 'read') || $user->hasRight('hrm', 'write_personal_information', 'write');
$permissiontowritehr = $user->hasRight('hrm', 'write_personal_information', 'write');
// Definition of fields for list
$arrayfields = array('u.rowid' => array('label' => "TechnicalID", 'checked' => '-1', 'position' => 5), 'u.login' => array('label' => "Login", 'checked' => '1', 'position' => 10), 'u.lastname' => array('label' => "Lastname", 'checked' => '1', 'position' => 15), 'u.firstname' => array('label' => "Firstname", 'checked' => '1', 'position' => 20), 'u.entity' => array('label' => "Entity", 'checked' => '1', 'position' => 50, 'enabled' => (string) (int) (\isModEnabled('multicompany') && !\getDolGlobalString('MULTICOMPANY_TRANSVERSE_MODE'))), 'u.gender' => array('label' => "Gender", 'checked' => '0', 'position' => 22), 'u.employee' => array('label' => "Employee", 'checked' => $contextpage == 'employeelist' ? '1' : '0', 'position' => 25), 'u.fk_user' => array('label' => "HierarchicalResponsible", 'checked' => '1', 'position' => 27, 'csslist' => 'maxwidth150'), 'u.accountancy_code' => array('label' => "AccountancyCode", 'checked' => '0', 'position' => 30), 'u.office_phone' => array('label' => "PhonePro", 'checked' => '1', 'position' => 31), 'u.user_mobile' => array('label' => "PhoneMobile", 'checked' => '1', 'position' => 32), 'u.email' => array('label' => "EMail", 'checked' => '1', 'position' => 35), 'co.label' => array('label' => "Country", 'checked' => '0', 'position' => 37), 'u.api_key' => array('label' => "ApiKey", 'checked' => '0', 'position' => 40, "enabled" => (string) (int) (\isModEnabled('api') && $user->admin)), 'u.fk_soc' => array('label' => "Company", 'checked' => $contextpage == 'employeelist' ? '0' : '1', 'position' => 45), 'u.ref_employee' => array('label' => "RefEmployee", 'checked' => '-1', 'position' => 50, 'enabled' => (string) (int) (\isModEnabled('hrm') && $permissiontoreadhr)), 'u.national_registration_number' => array('label' => "NationalRegistrationNumber", 'checked' => '-1', 'position' => 51, 'enabled' => (string) (int) (\isModEnabled('hrm') && $permissiontoreadhr)), 'u.job' => array('label' => "PostOrFunction", 'checked' => '-1', 'position' => 60), 'u.salary' => array('label' => "Salary", 'checked' => '-1', 'position' => 80, 'enabled' => (string) (int) (\isModEnabled('salaries') && $user->hasRight("salaries", "readall")), 'isameasure' => 1), 'u.thm' => array('label' => "THM", 'langs' => 'salaries', 'checked' => '-1', 'position' => 82, 'enabled' => '1', 'isameasure' => 1), 'u.datec' => array('label' => "DateCreation", 'checked' => '0', 'position' => 500), 'date_modification' => array('label' => "DateModificationShort", 'checked' => '0', 'position' => 500), 'u.import_key' => array('label' => "ImportId", 'checked' => '-1', 'position' => 800, 'enabled' => '1'), 'u.statut' => array('label' => "Status", 'checked' => '1', 'position' => 1000));
$arrayfields = \dol_sort_array($arrayfields, 'position');
// Init search fields
$search_all = \trim(\GETPOST('search_all', 'alphanohtml'));
$search_user = \GETPOST('search_user', 'alpha');
$search_rowid = \GETPOST('search_rowid', 'alpha');
$search_login = \GETPOST('search_login', 'alpha');
$search_lastname = \GETPOST('search_lastname', 'alpha');
$search_firstname = \GETPOST('search_firstname', 'alpha');
$search_gender = \GETPOST('search_gender', 'alpha');
$search_employee = \GETPOST('search_employee', 'alpha');
$search_accountancy_code = \GETPOST('search_accountancy_code', 'alpha');
$search_phonepro = \GETPOST('search_phonepro', 'alpha');
$search_phonemobile = \GETPOST('search_phonemobile', 'alpha');
$search_email = \GETPOST('search_email', 'alpha');
$search_country = \GETPOST('search_country', 'alpha');
$search_api_key = \GETPOST('search_api_key', 'alphanohtml');
$search_status = \GETPOST('search_status', 'intcomma');
$search_thirdparty = \GETPOST('search_thirdparty', 'alpha');
$search_job = \GETPOST('search_job', 'alpha');
$search_warehouse = \GETPOST('search_warehouse', 'alpha');
$search_supervisor = \GETPOST('search_supervisor', 'intcomma');
$search_categ = \GETPOST("search_categ", 'intcomma');
$search_datelastlogin = \GETPOSTDATE('search_datelastlogin', '', 'tzuserrel');
$search_datepreviouslogin = \GETPOSTDATE('search_datepreviouslogin', '', 'tzuserrel');
$searchCategoryUserOperator = 0;
$searchCategoryUserList = \GETPOST('search_category_user_list', 'array:int');
$catid = \GETPOSTINT('catid');
$catid = \GETPOSTINT('catid');
// Define value to know what current user can do on users
$permissiontoadd = \isModEnabled('multicompany') && !empty($user->entity) && \getDolGlobalString('MULTICOMPANY_TRANSVERSE_MODE') ? \false : !empty($user->admin) || $user->hasRight("user", "user", "write");
$canreaduser = !empty($user->admin) || $user->hasRight("user", "user", "read");
$canedituser = $permissiontoadd;
$candisableuser = \isModEnabled('multicompany') && !empty($user->entity) && \getDolGlobalString('MULTICOMPANY_TRANSVERSE_MODE') ? \false : !empty($user->admin) || $user->hasRight("user", "user", "delete");
$canreadgroup = $canreaduser;
$caneditgroup = $canedituser;
$error = 0;
$childids = $user->getAllChildIds(1);
$parameters = array('arrayfields' => &$arrayfields);
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Mass actions
$objectclass = 'User';
$objectlabel = 'User';
$uploaddir = $conf->user->dir_output;
/*
 * View
 */
$formother = new \FormOther($db);
$user2 = new \User($db);
$help_url = 'EN:Module_Users|FR:Module_Utilisateurs|ES:M&oacute;dulo_Usuarios|DE:Modul_Benutzer';
$morejs = array();
$morecss = array();
$morehtmlright = "";
// Build and execute select
// --------------------------------------------------------------------
$sql = "SELECT DISTINCT u.rowid, u.lastname, u.firstname, u.admin, u.fk_soc, u.login, u.office_phone, u.user_mobile, u.email, u.api_key, u.accountancy_code, u.gender, u.employee, u.photo,";
// Add fields from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListSelect', $parameters, $object);
$sql = \preg_replace('/,\\s*$/', '', $sql);
$sqlfields = $sql;
// Add table from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListFrom', $parameters, $object);
// Search for tag/category ($searchCategoryUserList is an array of ID)
$searchCategoryUserList = array($search_categ);
$searchCategoryUserSqlList = array();
$listofcategoryid = '';
// Add where from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListWhere', $parameters, $object);
// Count total nb of records
$nbtotalofrecords = '';
/* The fast and low memory method to get and count full list converts the sql into a sql count */
$sqlforcount = \preg_replace('/^' . \preg_quote($sqlfields, '/') . '/', 'SELECT COUNT(*) as nbtotalofrecords', $sql);
$sqlforcount = \preg_replace('/GROUP BY .*$/', '', $sqlforcount);
$resql = $db->query($sqlforcount);
$resql = $db->query($sql);
$num = $db->num_rows($resql);
$arrayofselected = \is_array($toselect) ? $toselect : array();
$param = '';
// List of mass actions available
$arrayofmassactions = array();
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);
$url = \DOL_URL_ROOT . '/user/card.php?action=create' . ($contextpage == 'employeelist' ? '&search_employee=1' : '') . '&leftmenu=';
$newcardbutton = '';
// Add code for pre mass action (confirmation or email presend form)
$topicmail = "SendUserRef";
$modelmail = "user";
$objecttmp = new \User($db);
$trackid = 'use' . $object->id;
$moreforfilter = '';
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object, $action);
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
$htmlofselectarray = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, \getDolGlobalString('MAIN_CHECKBOX_LEFT_COLUMN'));
// This also change content of $arrayfields
$selectedfields = $mode != 'kanban' ? $htmlofselectarray : '';
// Fields from hook
$parameters = array('arrayfields' => $arrayfields);
$reshook = $hookmanager->executeHooks('printFieldListOption', $parameters, $object);
$totalarray = array();
// Hook fields
$parameters = array('arrayfields' => $arrayfields, 'param' => $param, 'sortfield' => $sortfield, 'sortorder' => $sortorder, 'totalarray' => &$totalarray);
$reshook = $hookmanager->executeHooks('printFieldListTitle', $parameters, $object);
// Detect if we need a fetch on each output line
$needToFetchEachLine = 0;
// Loop on record
// --------------------------------------------------------------------
$i = 0;
$savnbfield = $totalarray['nbfield'];
$totalarray = array('val' => array('u.salary' => 0));
$imaxinloop = $limit ? \min($num, $limit) : $num;
$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $object, $action);