<?php

$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'create'/'add', 'edit'/'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : 'salestaxeslist';
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'alpha');
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$mode = \GETPOST('mode', 'aZ');
// The output mode ('list', 'kanban', 'hierarchy', 'calendar', ...)
$search_ref = \GETPOST('search_ref', 'alpha');
$search_label = \GETPOST('search_label', 'alpha');
$search_dateend_start = \dol_mktime(0, 0, 0, \GETPOSTINT('search_dateend_startmonth'), \GETPOSTINT('search_dateend_startday'), \GETPOSTINT('search_dateend_startyear'));
$search_dateend_end = \dol_mktime(23, 59, 59, \GETPOSTINT('search_dateend_endmonth'), \GETPOSTINT('search_dateend_endday'), \GETPOSTINT('search_dateend_endyear'));
$search_datepayment_start = \dol_mktime(0, 0, 0, \GETPOSTINT('search_datepayment_startmonth'), \GETPOSTINT('search_datepayment_startday'), \GETPOSTINT('search_datepayment_startyear'));
$search_datepayment_end = \dol_mktime(23, 59, 59, \GETPOSTINT('search_datepayment_endmonth'), \GETPOSTINT('search_datepayment_endday'), \GETPOSTINT('search_datepayment_endyear'));
$search_type = \GETPOST('search_type', 'intcomma');
$search_account = \GETPOST('search_account', 'alpha');
$search_amount = \GETPOST('search_amount', 'alpha');
$search_status = \GETPOST('search_status', 'intcomma');
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT('page');
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
$arrayfields = array('t.rowid' => array('checked' => '1', 'position' => 10, 'label' => "Ref"), 't.label' => array('checked' => '1', 'position' => 20, 'label' => "Label"), 't.datev' => array('checked' => '1', 'position' => 30, 'label' => "PeriodEndDate"), 't.fk_typepayment' => array('checked' => '1', 'position' => 50, 'label' => "DefaultPaymentMode"), 't.amount' => array('checked' => '1', 'position' => 90, 'label' => "Amount"), 't.datec' => array('checked' => '1', 'position' => 91, 'label' => "DateCreation"), 't.status' => array('checked' => '1', 'position' => 92, 'label' => "Status"));
$arrayfields = \dol_sort_array($arrayfields, 'position');
$object = new \Tva($db);
$permissiontoadd = $user->hasRight('tax', 'charges', 'creer');
$permissiontodelete = $user->hasRight('tax', 'charges', 'supprimer');
// Security check
$socid = \GETPOSTINT('socid');
$result = \restrictedArea($user, 'tax', '', 'tva', 'charges');
/*
 * Actions
 */
$parameters = array('socid' => $socid);
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Mass actions
$objectclass = 'Tva';
$objectlabel = 'Tva';
$uploaddir = $conf->tax->dir_output;
/*
 * View
 */
$form = new \Form($db);
$formother = new \FormOther($db);
$formfile = new \FormFile($db);
$tva_static = new \Tva($db);
$bankstatic = new \Account($db);
$accountingjournal = new \AccountingJournal($db);
$bankline = new \AccountLine($db);
$now = \dol_now();
$title = $langs->trans("VATDeclarations");
//$help_url = "EN:Module_MyObject|FR:Module_MyObject_FR|ES:Módulo_MyObject";
$help_url = '';
// Build and execute select
// --------------------------------------------------------------------
$sql = 'SELECT t.rowid, t.amount, t.label, t.datec, t.datev, t.paye as status, t.fk_typepayment as type, t.fk_account,';
$sqlfields = $sql;
// Count total nb of records
$nbtotalofrecords = '';
/* The fast and low memory method to get and count full list converts the sql into a sql count */
$sqlforcount = \preg_replace('/^' . \preg_quote($sqlfields, '/') . '/', 'SELECT COUNT(*) as nbtotalofrecords', $sql);
$sqlforcount = \preg_replace('/GROUP BY .*$/', '', $sqlforcount);
$resql = $db->query($sqlforcount);
$resql = $db->query($sql);
$num = $db->num_rows($resql);
$arrayofselected = \is_array($toselect) ? $toselect : array();
$param = '';
// List of mass actions available
$arrayofmassactions = array();
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);
$moreforfilter = '';
$url = \DOL_URL_ROOT . '/compta/tva/card.php?action=create';
$newcardbutton = '';
// Add code for pre mass action (confirmation or email presend form)
$topicmail = "SendVAT";
$modelmail = "vat";
$objecttmp = new \Tva($db);
$trackid = 'vat' . $object->id;
$varpage = empty($contextpage) ? $_SERVER['PHP_SELF'] : $contextpage;
$selectedfields = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, \getDolGlobalString('MAIN_CHECKBOX_LEFT_COLUMN'));
$moreforfilter = '';
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object, $action);
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
$htmlofselectarray = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, \getDolGlobalString('MAIN_CHECKBOX_LEFT_COLUMN'));
// This also change content of $arrayfields with user setup
$selectedfields = $mode != 'kanban' ? $htmlofselectarray : '';
// Fields from hook
$parameters = array('arrayfields' => $arrayfields);
$reshook = $hookmanager->executeHooks('printFieldListOption', $parameters, $object, $action);
$totalarray = array();
// Hook fields
$parameters = array('arrayfields' => $arrayfields, 'param' => $param, 'sortfield' => $sortfield, 'sortorder' => $sortorder);
$reshook = $hookmanager->executeHooks('printFieldListTitle', $parameters, $object, $action);
// Loop on record
// --------------------------------------------------------------------
$i = 0;
$savnbfield = $totalarray['nbfield'];
$totalarray = array();
$imaxinloop = $limit ? \min($num, $limit) : $num;
$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $object, $action);