<?php

$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : 'bomlist';
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$mode = \GETPOST('mode', 'alpha');
// mode view for result
// Load variable for pagination
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
// If $page is not defined, or '' or -1 or if we click on clear filters or if we select empty mass action
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
// Initialize a technical objects
$object = new \PaymentSalary($db);
$extrafields = new \ExtraFields($db);
$diroutputmassaction = $conf->user->dir_output . '/temp/massgeneration/' . $user->id;
$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');
$search_ref = \GETPOST('search_ref', 'alpha');
$search_ref_salary = \GETPOST('search_ref_salary', 'alpha');
$search_user = \GETPOST('search_user', 'alpha');
$search_label = \GETPOST('search_label', 'alpha');
$search_date_start = \dol_mktime(0, 0, 0, \GETPOSTINT('search_date_startmonth'), \GETPOSTINT('search_date_startday'), \GETPOSTINT('search_date_startyear'));
$search_date_end = \dol_mktime(23, 59, 59, \GETPOSTINT('search_date_endmonth'), \GETPOSTINT('search_date_endday'), \GETPOSTINT('search_date_endyear'));
$search_dateep_start = \dol_mktime(0, 0, 0, \GETPOSTINT('search_dateep_startmonth'), \GETPOSTINT('search_dateep_startday'), \GETPOSTINT('search_dateep_startyear'));
$search_dateep_end = \dol_mktime(23, 59, 59, \GETPOSTINT('search_dateep_endmonth'), \GETPOSTINT('search_dateep_endday'), \GETPOSTINT('search_dateep_endyear'));
$search_amount = \GETPOST('search_amount', 'alpha');
$search_account = \GETPOST('search_account', 'alpha');
$search_fk_bank = \GETPOST('search_fk_bank', 'alpha');
$search_chq_number = \GETPOST('search_chq_number', 'alpha');
$search_type_id = \GETPOST('search_type_id', 'int');
$childids = $user->getAllChildIds(1);
// Initialize array of search criteria
$search_all = \GETPOST("search_all", 'alpha');
$search = array();
// List of fields to search into when doing a "search in all"
$fieldstosearchall = array();
// Definition of array of fields for columns
$arrayfields = array();
$permissiontoread = $user->hasRight('salaries', 'read');
$permissiontoadd = $user->hasRight('salaries', 'write');
$permissiontodelete = $user->hasRight('salaries', 'delete');
// Security check
$socid = \GETPOSTINT("socid");
/*
 * Actions
 */
$error = 0;
$parameters = array();
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Mass actions
$objectclass = 'PaymentSalary';
$objectlabel = 'SalariesPayments';
$uploaddir = $conf->salaries->dir_output;
/*
 * View
 */
$form = new \Form($db);
$salstatic = new \Salary($db);
$paymentsalstatic = new \PaymentSalary($db);
$userstatic = new \User($db);
$accountstatic = new \Account($db);
$accountlinestatic = new \AccountLine($db);
$now = \dol_now();
//$help_url="EN:Module_BillOfMaterials|FR:Module_BillOfMaterials_FR|ES:Módulo_BillOfMaterials";
$help_url = '';
$title = $langs->trans('SalariesPayments');
$sql = "SELECT u.rowid as uid, u.lastname, u.firstname, u.login, u.email, u.admin, u.photo, u.gender, u.salary as current_salary, u.fk_soc as fk_soc, u.statut as status,";
// Count total nb of records
$nbtotalofrecords = '';
$resql = $db->query($sql);
$arrayofselected = \is_array($toselect) ? $toselect : array();
$param = '';
// List of mass actions available
$arrayofmassactions = array();
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);
$url = \DOL_URL_ROOT . '/salaries/card.php?action=create';
$newcardbutton = '';
$newcardbutton = \dolGetButtonTitle($langs->trans('NewSalaryPayment'), '', 'fa fa-plus-circle', $url, '', $user->hasRight('salaries', 'write'));
$moreforfilter = '';
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
//$selectedfields = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage); // This also change content of $arrayfields
$selectedfields = '';
// Fields from hook
$parameters = array('arrayfields' => $arrayfields);
$reshook = $hookmanager->executeHooks('printFieldListOption', $parameters, $object);
$totalarray = array();
// Hook fields
$parameters = array('arrayfields' => $arrayfields, 'param' => $param, 'sortfield' => $sortfield, 'sortorder' => $sortorder);
$reshook = $hookmanager->executeHooks('printFieldListTitle', $parameters, $object);
// Detect if we need a fetch on each output line
$needToFetchEachLine = 0;
// Loop on record
// --------------------------------------------------------------------
$i = 0;
$savnbfield = $totalarray['nbfield'];
$totalarray = array();
$imaxinloop = $limit ? \min($num, $limit) : $num;
$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $object);