<?php

// autoload_real.php @generated by Composer
class ComposerAutoloaderInit51cd53f153efda61d1f1f814155d1c4a
{
    private static $loader;
    public static function loadClassLoader($class)
    {
    }
    /**
     * @return \Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
    }
}
/**
 * @param string $fileIdentifier
 * @param string $file
 * @return void
 */
function composerRequire51cd53f153efda61d1f1f814155d1c4a($fileIdentifier, $file)
{
}