<?php

$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : 'categorylist';
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$id = \GETPOSTINT('id');
$label = \GETPOST('label', 'alpha');
$removeelem = \GETPOSTINT('removeelem');
$elemid = \GETPOSTINT('elemid');
// Load variable for pagination
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
// If $page is not defined, or '' or -1 or if we click on clear filters or if we select empty mass action
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
$object = new \Categorie($db);
$result = $object->fetch($id, $label);
// Security check
$result = \restrictedArea($user, 'categorie', $object->id, '&category');
$type = $object->type;
$extrafields = new \ExtraFields($db);
$parameters = array('type' => $type, 'id' => $id, 'label' => $label);
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Test on permission not required here. Done later according to type of object.
$tmpobject = \null;
$elementtype = '';
// Test on permission not required here. Done just after depending on object type
$newobject = \null;
$elementtype = '';
/*
 * View
 */
$form = new \Form($db);
$formother = new \FormOther($db);
$arrayofjs = array('/includes/jquery/plugins/jquerytreeview/jquery.treeview.js', '/includes/jquery/plugins/jquerytreeview/lib/jquery.cookie.js');
$arrayofcss = array('/includes/jquery/plugins/jquerytreeview/jquery.treeview.css');
$help_url = '';
$title = $langs->trans("Categories");
$head = \categories_prepare_head($object, $type);
$backtolist = \GETPOST('backtolist') ? \GETPOST('backtolist') : \DOL_URL_ROOT . '/categories/categorie_list.php?leftmenu=cat&type=' . \urlencode($type);
$linkback = '<a href="' . \dol_sanitizeUrl($backtolist) . '">' . $langs->trans("BackToList") . '</a>';
$morehtmlref = '<br><div class="refidno"><a href="' . \DOL_URL_ROOT . '/categories/categorie_list.php?leftmenu=cat&type=' . \urlencode($type) . '">' . $langs->trans("Root") . '</a>';
$ways = $object->print_all_ways("auto", '', 1, 0, 1);
$reshook = $hookmanager->executeHooks('addMoreActionsButtons', $parameters, $object, $action);
$newcardbutton = '';
$cats = $object->get_filles();
// List of mass actions available
$arrayofmassactions = array();
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);
$typeid = $type;
$permission = $user->hasRight('commande', 'creer');
$objects = $object->getObjectsInCateg($type, 0, $limit, $offset);
$permission = $user->hasRight('facture', 'creer');
$objects = $object->getObjectsInCateg($type, 0, $limit, $offset);
$permission = $user->hasRight('fournisseur', 'commande', 'creer');
$objects = $object->getObjectsInCateg($type, 0, $limit, $offset);
$permission = $user->hasRight('fournisseur', 'facture', 'creer');
$objects = $object->getObjectsInCateg($type, 0, $limit, $offset);
// Note that $action and $object may have been modified by some hooks
$parameters = array('type' => $type, 'id' => $id, 'label' => $label);
$reshook = $hookmanager->executeHooks('addMoreCategoriesList', $parameters, $object, $action);