<?php

/**
 *  \class      ModeleGenPassword
 *  \brief      Parent class for password rules/management modules
 */
abstract class ModeleGenPassword
{
    /**
     * @var string Error code (or message)
     */
    public $error = '';
    /**
     * 		Return if a module can be used or not
     *
     *      @return		boolean     true if module can be used
     */
    public function isEnabled()
    {
    }
    /**
     *		Return description of module
     *
     *      @return     string      Description of text
     */
    public function getDescription()
    {
    }
    /**
     *  Return an example of password generated by this module
     *
     *  @return     string      Example of password
     */
    public function getExample()
    {
    }
    /**
     *  Build new password
     *
     *  @return     string      Return a new generated password
     */
    public function getNewGeneratedPassword()
    {
    }
    /**
     * 		Validate a password
     *
     *		@param		string	$password	Password to check
     *      @return     int					0 if KO, >0 if OK
     */
    public function validatePassword($password)
    {
    }
}