<?php

/**
 *	    \class      modGeneratePassStandard
 *		\brief      Class to generate a password according to a dolibarr standard rule (8 random chars)
 */
class modGeneratePassStandard extends \ModeleGenPassword
{
    /**
     * @var int ID
     */
    public $id;
    public $length;
    /**
     * @var DoliDB Database handler.
     */
    public $db;
    public $conf;
    public $lang;
    public $user;
    /**
     *	Constructor
     *
     *  @param		DoliDB		$db			Database handler
     *	@param		Conf		$conf		Handler de conf
     *	@param		Translate	$langs		Handler de langue
     *	@param		User		$user		Handler du user connecte
     */
    public function __construct($db, $conf, $langs, $user)
    {
    }
    /**
     *		Return description of module
     *
     *      @return     string      Description of module
     */
    public function getDescription()
    {
    }
    /**
     * 		Return an example of password generated by this module
     *
     *      @return     string      Example of password
     */
    public function getExample()
    {
    }
    /**
     * 		Build new password
     *
     *      @return     string      Return a new generated password
     */
    public function getNewGeneratedPassword()
    {
    }
    /**
     *  Validate a password
     *
     *  @param      string  $password   Password to check
     *  @return     int                 0 if KO, >0 if OK
     */
    public function validatePassword($password)
    {
    }
}