<?php

// Get parameters
$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : 'ticketlist';
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$mode = \GETPOST('mode', 'alpha');
$id = \GETPOSTINT('id');
$socid = \GETPOSTINT('socid');
$contractid = \GETPOSTINT('contractid');
$projectid = \GETPOSTINT('projectid');
$project_ref = \GETPOST('project_ref', 'alpha');
$search_societe = \GETPOST('search_societe', 'alpha');
$search_fk_project = \GETPOSTINT('search_fk_project') ? \GETPOSTINT('search_fk_project') : \GETPOSTINT('projectid');
$search_fk_contract = \GETPOSTINT('search_fk_contract') ? \GETPOSTINT('search_fk_contract') : \GETPOSTINT('contractid');
$search_date_start = \dol_mktime(0, 0, 0, \GETPOSTINT('search_date_startmonth'), \GETPOSTINT('search_date_startday'), \GETPOSTINT('search_date_startyear'));
$search_date_end = \dol_mktime(23, 59, 59, \GETPOSTINT('search_date_endmonth'), \GETPOSTINT('search_date_endday'), \GETPOSTINT('search_date_endyear'));
$search_dateread_start = \dol_mktime(0, 0, 0, \GETPOSTINT('search_dateread_startmonth'), \GETPOSTINT('search_dateread_startday'), \GETPOSTINT('search_dateread_startyear'));
$search_dateread_end = \dol_mktime(23, 59, 59, \GETPOSTINT('search_dateread_endmonth'), \GETPOSTINT('search_dateread_endday'), \GETPOSTINT('search_dateread_endyear'));
$search_dateclose_start = \dol_mktime(0, 0, 0, \GETPOSTINT('search_dateclose_startmonth'), \GETPOSTINT('search_dateclose_startday'), \GETPOSTINT('search_dateclose_startyear'));
$search_dateclose_end = \dol_mktime(23, 59, 59, \GETPOSTINT('search_dateclose_endmonth'), \GETPOSTINT('search_dateclose_endday'), \GETPOSTINT('search_dateclose_endyear'));
// Load variable for pagination
$limit = \GETPOSTINT('limit') ? \GETPOSTINT('limit') : $conf->liste_limit;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
// Initialize a technical objects
$object = new \Ticket($db);
$extrafields = new \ExtraFields($db);
$diroutputmassaction = $conf->ticket->dir_output . '/temp/massgeneration/' . $user->id;
$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');
/*if (GETPOST('search_fk_status', 'alpha') == 'non_closed') {
	$_GET['search_fk_statut'][] = 'openall'; // For backward compatibility
}*/
// Initialize array of search criteria
$search_all = \trim(\GETPOST("search_all", 'alphanohtml'));
$search = array();
// List of fields to search into when doing a "search in all"
$fieldstosearchall = array();
// Definition of array of fields for columns
$arrayfields = array();
$arrayfields = \dol_sort_array($arrayfields, 'position');
// Store current page url
$url_page_current = \DOL_URL_ROOT . '/ticket/list.php';
$permissiontoread = $user->hasRight('ticket', 'read');
$permissiontoadd = $user->hasRight('ticket', 'write');
$permissiontodelete = $user->hasRight('ticket', 'delete');
$error = 0;
$parameters = array('arrayfields' => &$arrayfields);
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
// Mass actions
$objectclass = 'Ticket';
$objectlabel = 'Ticket';
$uploaddir = $conf->ticket->dir_output;
/*
 * View
 */
$form = new \Form($db);
$formTicket = new \FormTicket($db);
$now = \dol_now();
$user_temp = new \User($db);
$socstatic = new \Societe($db);
$help_url = '';
$moretitle = '';
$moretitle = $langs->trans("ThirdParty") . ' - ';
$title = $moretitle . $langs->trans('Tickets');
$morejs = array();
$morecss = array();
// Build and execute select
// --------------------------------------------------------------------
$sql = 'SELECT ';
// Add fields from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListSelect', $parameters, $object, $action);
$sql = \preg_replace('/,\\s*$/', '', $sql);
$sqlfields = $sql;
// Add table from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListFrom', $parameters, $object);
// Add where from hooks
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldListWhere', $parameters, $object);
// Count total nb of records
$nbtotalofrecords = '';
/* The fast and low memory method to get and count full list converts the sql into a sql count */
$sqlforcount = \preg_replace('/^' . \preg_quote($sqlfields, '/') . '/', 'SELECT COUNT(*) as nbtotalofrecords', $sql);
$sqlforcount = \preg_replace('/GROUP BY .*$/', '', $sqlforcount);
$resql = $db->query($sqlforcount);
$resql = $db->query($sql);
$num = $db->num_rows($resql);
$socstat = new \Societe($db);
$res = $socstat->fetch($socid);
$projectstat = new \Project($db);
$arrayofselected = \is_array($toselect) ? $toselect : array();
$param = '';
// Add $param from hooks
$parameters = array('param' => &$param);
$reshook = $hookmanager->executeHooks('printFieldListSearchParam', $parameters, $object);
// List of mass actions available
$arrayofmassactions = array();
$massactionbutton = $form->selectMassAction('', $arrayofmassactions);
$url = \DOL_URL_ROOT . '/ticket/card.php?action=create&mode=init' . ($socid ? '&socid=' . $socid : '') . ($projectid ? '&origin=projet_project&originid=' . $projectid : '');
$newcardbutton = '';
$picto = 'ticket';
// Add code for pre mass action (confirmation or email presend form)
$topicmail = "SendTicketRef";
$modelmail = "ticket";
$objecttmp = new \Ticket($db);
$trackid = 'tic' . $object->id;
$moreforfilter = '';
/*$moreforfilter.='<div class="divsearchfield">';
$moreforfilter.= $langs->trans('MyFilter') . ': <input type="text" name="search_myfield" value="'.dol_escape_htmltag($search_myfield).'">';
$moreforfilter.= '</div>';*/
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldPreListTitle', $parameters, $object, $action);
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
$selectedfields = $form->multiSelectArrayWithCheckbox('selectedfields', $arrayfields, $varpage, \getDolGlobalString('MAIN_CHECKBOX_LEFT_COLUMN'));
// Fields from hook
$parameters = array('arrayfields' => $arrayfields);
$reshook = $hookmanager->executeHooks('printFieldListOption', $parameters, $object, $action);
$totalarray = array();
// Hook fields
$parameters = array('arrayfields' => $arrayfields, 'param' => $param, 'sortfield' => $sortfield, 'sortorder' => $sortorder, 'totalarray' => &$totalarray);
$reshook = $hookmanager->executeHooks('printFieldListTitle', $parameters, $object, $action);
// Detect if we need a fetch on each output line
$needToFetchEachLine = 0;
// Loop on record
// --------------------------------------------------------------------
$i = 0;
$savnbfield = $totalarray['nbfield'];
$totalarray = array();
$imaxinloop = $limit ? \min($num, $limit) : $num;
$cacheofoutputfield = array();
$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $object);
$hidegeneratedfilelistifempty = 1;
$formfile = new \FormFile($db);
// Show list of available documents
$urlsource = $_SERVER['PHP_SELF'] . '?sortfield=' . $sortfield . '&sortorder=' . $sortorder;
$filedir = $diroutputmassaction;
$genallowed = $permissiontoread;
$delallowed = $permissiontoadd;