<?php

/**
 *	Class to generate a password according to a dolibarr standard rule (12 random chars)
 */
class modCaptchaStandard extends \ModeleCaptcha
{
    /**
     * @var string ID
     */
    public $id;
    /**
     * @var string
     */
    public $picto = 'fa-shield-alt';
    /**
     *	Constructor
     *
     *  @param		DoliDB		$db			Database handler
     *	@param		Conf		$conf		Handler de conf
     *	@param		Translate	$langs		Handler de langue
     *	@param		User		$user		Handler du user connected
     */
    public function __construct($db, $conf, $langs, $user)
    {
    }
    /**
     *		Return description of module
     *
     *      @return     string      Description of module
     */
    public function getDescription()
    {
    }
    /**
     * 		Return an example of password generated by this module
     *
     *      @return     string      Example of password
     */
    public function getExample()
    {
    }
    /**
     * 	Return the HTML content to output on a form that need the captcha
     *
     *  @param		string	$php_self	An URL for the a href link
     *  @return     string				The HTML code to output
     */
    public function getCaptchaCodeForForm($php_self = '')
    {
    }
    /**
     * 	Validate a captcha
     * 	This function is called after a log to validate a captcha, before validating a password.
     *
     *  @return     int					0 if KO, >0 if OK
     */
    public function validateCodeAfterLoginSubmit()
    {
    }
}