<?php

/**
 *  Parent class for password rules/management modules
 */
abstract class ModeleCaptcha
{
    /**
     * @var string
     */
    public $id;
    /**
     * @var string
     */
    public $version;
    /**
     * @var string
     */
    public $picto = 'generic';
    /**
     * @var string Error code (or message)
     */
    public $error = '';
    /**
     * @var DoliDB Database handler.
     */
    public $db;
    /**
     * @var Conf dolibarr conf
     */
    public $conf;
    /**
     * @var Translate Translate Object
     */
    public $langs;
    /**
     * @var User user
     */
    public $user;
    /**
     * 		Return if a module can be used or not
     *
     *      @return		boolean     true if module can be used
     */
    public function isEnabled()
    {
    }
    /**
     *		Return description of module
     *
     *      @return     string      Description of module
     */
    public function getDescription()
    {
    }
    /**
     *  Return an example of password generated by this module
     *
     *  @return     string      	Example of captcha
     */
    public function getExample()
    {
    }
    /**
     * 	Return the HTML content to output on a form that need the captcha
     *
     *  @param		string	$php_self	An URL for the a href link
     *  @return     string				The HTML code to output
     */
    public function getCaptchaCodeForForm($php_self = '')
    {
    }
    /**
     * 	Validate a captcha
     * 	This function is called after a log to validate a captcha, before validating a password.
     *
     *  @return     int					0 if KO, >0 if OK
     */
    public function validateCodeAfterLoginSubmit()
    {
    }
}