<?php

//
$documentation = new \Documentation($db);
$morejs = ['/includes/ace/src/ace.js', '/includes/ace/src/ext-statusbar.js', '/includes/ace/src/ext-language_tools.js'];
$lines = array('<h1>Example heading <span class="badge badge-secondary">New</span></h1>', '<h2>Example heading <span class="badge badge-secondary">New</span></h2>', '<h3>Example heading <span class="badge badge-secondary">New</span></h3>', '<h4>Example heading <span class="badge badge-secondary">New</span></h4>', '<h5>Example heading <span class="badge badge-secondary">New</span></h5>', '<h6>Example heading <span class="badge badge-secondary">New</span></h6>');
$lines = array('<button type="button" class="button">', '	Notifications <span class="badge badge-primary">4</span>', '</button>');
$lines = array('<button type="button" class="button">', '	Profile <span class="badge badge-primary" aria-label="9 unread messages" >9</span>', '	<span class="sr-only">unread messages</span>', '</button>');
$lines = array('<span class="badge badge-primary">Primary</span>', '<span class="badge badge-secondary">Secondary</span>', '<span class="badge badge-success">Success</span>', '<span class="badge badge-danger">Danger</span>', '<span class="badge badge-warning">Warning</span>', '<span class="badge badge-info">Info</span>', '<span class="badge badge-light">Light</span>', '<span class="badge badge-dark">Dark</span>');
$lines = array();
$lines = array('<span class="badge badge-pill badge-primary">Primary</span>', '<span class="badge badge-pill badge-secondary">Secondary</span>', '<span class="badge badge-pill badge-success">Success</span>', '<span class="badge badge-pill badge-danger">Danger</span>', '<span class="badge badge-pill badge-warning">Warning</span>', '<span class="badge badge-pill badge-info">Info</span>', '<span class="badge badge-pill badge-light">Light</span>', '<span class="badge badge-pill badge-dark">Dark</span>');
$lines = array('<span class="badge badge-dot badge-primary"></span>', '<span class="badge badge-dot badge-secondary"></span>', '<span class="badge badge-dot badge-success"></span>', '<span class="badge badge-dot badge-danger"></span>', '<span class="badge badge-dot badge-warning"></span>', '<span class="badge badge-dot badge-info"></span>', '<span class="badge badge-dot badge-light"></span>', '<span class="badge badge-dot badge-dark"></span>');
$lines = array('<a href="#" class="badge badge-primary">Primary</a>', '<a href="#" class="badge badge-secondary">Secondary</a>', '<a href="#" class="badge badge-success">Success</a>', '<a href="#" class="badge badge-danger">Danger</a>', '<a href="#" class="badge badge-warning">Warning</a>', '<a href="#" class="badge badge-info">Info</a>', '<a href="#" class="badge badge-light">Light</a>', '<a href="#" class="badge badge-dark">Dark</a>');
$lines = array("<?php ", "/**", " * Function dolGetBadge", " *", " * @param  string  \$label  label of badge no html : use in alt attribute for accessibility", " * @param  string  \$html   optional : label of badge with html", " * @param  string  \$type   type of badge : Primary Secondary Success Danger Warning Info Light Dark status0 status1 status2 status3 status4 status5 status6 status7 status8 status9", " * @param  string  \$mode   Default '' , 'pill', 'dot'", " * @param  string  \$url    the url for link", " * ... See more: core/lib/functions.lib.php ", "*/", "", "print dolGetBadge('your label for accessibility', 'your label <u>with</u> <em>html</em>', 'primary');", "print dolGetBadge('your label for accessibility', 'your label <u>with</u> <em>html</em>', 'danger', 'pill');", "print dolGetBadge('your label for accessibility', 'your label', 'warning', 'dot');");