<?php

//
$documentation = new \Documentation($db);
$morejs = ['/includes/ace/src/ace.js', '/includes/ace/src/ext-statusbar.js', '/includes/ace/src/ext-language_tools.js'];
$label = 'My action label used for accessibility visually for impaired people';
$user_right = 1;
$html = '<span class="fa fa-clone paddingright" aria-hidden="true"></span> My default action';
$action_type = 'default';
$id = 'button-id-1';
$url = '#' . $id;
$html = '<span class="fa fa-trash-alt paddingright" aria-hidden="true"></span> My delete action';
$action_type = 'delete';
$id = 'button-id-2';
$url = '#' . $id;
$html = '<span class="fa fa-radiation paddingright" aria-hidden="true"></span> My danger action';
$action_type = 'danger';
$id = 'button-id-3';
$url = '#' . $id;
$user_right = 0;
$html = '<span class="fa fa-clone paddingright" aria-hidden="true"></span> My default action';
$action_type = 'default';
$id = 'button-id-4';
$url = '#' . $id;
$html = '<span class="fa fa-trash-alt paddingright" aria-hidden="true"></span> My delete action';
$action_type = 'delete';
$id = 'button-id-5';
$url = '#' . $id;
$html = '<span class="fa fa-radiation paddingright" aria-hidden="true"></span> My danger action';
$action_type = 'danger';
$id = 'button-id-6';
$url = '#' . $id;
$lines = array('<?php', '/**', ' * Function dolGetButtonAction', ' *', ' * $label 		Label or tooltip of button if $text is provided. Also used as tooltip in title attribute. Can be escaped HTML content or full simple text.', ' * $html		Optional : short label on button. Can be escaped HTML content or full simple text.', ' * $actionType	default, danger, email, clone, cancel, delete, ...', ' * $url 		Url for link or array of subbutton description', ' * $id 		Attribute id of action button. Example \'action-delete\'. This can be used for full ajax confirm if this code is reused into the ->formconfirm() method.', ' * $userRight 	User action right / 0 = No, 1 = Yes', ' * $params 	Various params', ' * ', ' * See more in core/lib/functions.lib.php', ' */', 'print dolGetButtonAction($label, $html, $actionType, $url, $id, $userRight, $params);');
$userRight = 1;
$html = '<span class="fa fa-clone" paddingright" aria-hidden="true"></span> My default action';
$actionType = 'default';
$id = 'button-id-7';
$url = '#' . $id;
$params = array('confirm' => []);
$html = '<span class="fa fa-trash-alt paddingright" aria-hidden="true"></span> My delete action';
$actionType = 'delete';
$id = 'button-id-8';
$url = $_SERVER['PHP_SELF'] . '?token=' . \newToken() . '#' . $id;
$params = array('confirm' => array('url' => 'your confirm action url', 'title' => 'Your title to display', 'action-btn-label' => 'Your confirm label', 'cancel-btn-label' => 'Your cancel label', 'content' => 'Content to display  with <strong>HTML</strong> compatible <ul><li>test 01</li><li>test 02</li><li>test 03</li></ul>'));
$userRight = 0;
$html = '<span class="fa fa-clone" ></span> My default action';
$actionType = 'delete';
$id = 'button-id-9';
$url = '#' . $id;
$params = array('confirm' => []);
$lines = array('<?php', '// Default parameters', '$params = array(', '	\'confirm\' => [],', ');', '', '// Custom parameters', '$params = array(', '	\'confirm\' => array(', '		\'url\' => \'your confirm action url\',', '		\'title\' => \'Your title to display\',', '		\'action-btn-label\' => \'Your confirm label\',', '		\'cancel-btn-label\' => \'Your cancel label\',', '		\'content\' => \'Content to display  with <strong>HTML</strong> compatible <ul><li>test 01</li><li>test 02</li><li>test 03</li></ul>\',', '	)', ');', '', 'print dolGetButtonAction($label, $html, $actionType, $url, $id, $userRight, $params);');
$userRight = 1;
$html = '<span class="fa fa-clone" paddingright" aria-hidden="true"></span> My default action';
$actionType = 'default';
$id = 'button-id-7';
$submenu_url = \str_replace(\DOL_URL_ROOT, '', $_SERVER['PHP_SELF']);
$url = array(array('lang' => 'documentation@documentation', 'url' => $submenu_url . '#' . $id, 'label' => 'My SubAction 1', 'perm' => \true, 'enabled' => \true), array('lang' => 'documentation@documentation', 'url' => $submenu_url . '#' . $id, 'label' => 'My SubAction 2', 'perm' => \false, 'enabled' => \true));
$params = array();
$lines = array('<?php', '// Simple button', '$url = \'url_script\';', 'print dolGetButtonAction($label, $html, $actionType, $url, $id, $userRight, $params);', '', '// Dropdown button', '$url = array(', '	array(', '		\'lang\' => \'langfile\',', '		\'url\' => \'url_script_1\', // Url without DOL_URL_ROOT', '		\'label\' => \'My SubAction 1\',', '		\'perm\' => 1, // The user have the rights', '	),', '	array(', '		\'lang\' => \'langfile\',', '		\'url\' => \'url_script_2\', // Url without DOL_URL_ROOT', '		\'label\' => \'My SubAction 2\',', '		\'perm\' => 0, // The user does not have the rights', '	),', ');', 'print dolGetButtonAction($label, $html, $actionType, $url, $id, $userRight, $params);');
$btnLabel = $langs->trans('Label');
$btnLabel = $langs->trans('Reset');
$lines = array('<?php', '$btnLabel = $langs->trans(\'Label\');', 'print \' <button class="btn-low-emphasis --btn-icon" title="\'.dol_escape_htmltag($btnLabel).\'" aria-label="\'.dol_escape_htmltag($btnLabel).\'" >\'.img_picto($btnLabel, \'fa-arrow-right\', \'aria-hidden="true"\', 0, 0, 1).\'</button>\';', '', '$btnLabel = $langs->trans(\'Reset\');', 'print \' <button class="btn-low-emphasis --btn-icon" title="\'.dol_escape_htmltag($btnLabel).\'" aria-label="\'.dol_escape_htmltag($btnLabel).\'" >\'.img_picto($btnLabel, \'eraser\', \'aria-hidden="true"\', 0, 0, 1).\'</button>\';');
$btnLabel = $langs->trans('Label');
$lines = array('<?php', '$btnLabel = $langs->trans(\'Label\');', '$status = 0; // Not Enough Permissions', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-file\', \'#\', \'\', $status);', '$status = 1; // Active', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-file\', \'#\', \'\', $status);', '$status = 2; // Active and selected', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-file\', \'#\', \'\', $status);', '$status = -1; // Functionality is disabled', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-file\', \'#\', \'\', $status);', '$status = -2; // Disabled without info', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-file\', \'#\', \'\', $status);');
$btnLabel = $langs->trans('Label', 'php');
$lines = array('<?php', '$btnLabel = $langs->trans(\'Label\');', '$status = 0; // Not Enough Permissions', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-download\', \'#\', \'\', $status, [\'forcenohideoftext\'=>1]);', '$status = 1; // Active', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-download\', \'#\', \'\', $status, [\'forcenohideoftext\'=>1]);', '$status = 2; // Active and selected', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-download\', \'#\', \'\', $status, [\'forcenohideoftext\'=>1]);', '$status = -1; // Functionality is disabled', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-download\', \'#\', \'\', $status, [\'forcenohideoftext\'=>1]);', '$status = -2; // Disabled without info', 'print dolGetButtonTitle($btnLabel, \'\', \'fa fa-download\', \'#\', \'\', $status, [\'forcenohideoftext\'=>1]);');