<?php

//
$documentation = new \Documentation($db);
$morejs = ['/includes/ace/src/ace.js', '/includes/ace/src/ext-statusbar.js', '/includes/ace/src/ext-language_tools.js'];
$lines = array('<div class="progress xxs" title="10%">', '    <div class="progress-bar" role="progressbar" style="width: 10%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress xs" title="20%">', '    <div class="progress-bar" role="progressbar" style="width: 20%" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress sm" title="40%">', '    <div class="progress-bar" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress" title="80%">', '    <div class="progress-bar" role="progressbar" style="width: 80%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>', '</div>');
$lines = array('<div class="progress spaced" title="40%">', '    <div class="progress-bar" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>');
$lines = array('<div class="progress" title="40%">', '    <div class="progress-bar progress-bar-success" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress" title="40%">', '    <div class="progress-bar progress-bar-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress" title="40%">', '    <div class="progress-bar progress-bar-info" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress" title="40%">', '    <div class="progress-bar progress-bar-danger" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '');
$lines = array('<div class="progress progress-striped" title="40%">', '    <div class="progress-bar progress-bar-success" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress progress-striped" title="40%">', '    <div class="progress-bar progress-bar-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress progress-striped" title="40%">', '    <div class="progress-bar progress-bar-info" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress progress-striped" title="40%">', '    <div class="progress-bar progress-bar-danger" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '');
$lines = array('<div class="progress progress-striped" title="40%">', '    <div class="progress-bar progress-bar-success" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress progress-striped" title="40%">', '    <div class="progress-bar progress-bar-warning" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress progress-striped" title="40%">', '    <div class="progress-bar progress-bar-info" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '<div class="progress progress-striped" title="40%">', '    <div class="progress-bar progress-bar-danger" role="progressbar" style="width: 40%" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>', '</div>', '', '');