<?php

\define('NOREQUIRESOC', '1');
\define('NOCSRFCHECK', 1);
\define('NOTOKENRENEWAL', 1);
\define('NOLOGIN', 1);
\define('NOREQUIREHTML', 1);
\define('NOREQUIREAJAX', '1');
\define('NOSESSION', '1');
\define('NOREQUIREMENU', '1');
$n = 1;
$label = 'My action label used for accessibility visually for impaired people';
$html = '<span class="fa fa-clone" ></span> My default action';
$actionType = 'default';
$id = 'mybuttonid' . $n;
$url = '#' . $id;
$userRight = 1;
$params = array();
$html = '<span class="fa fa-clone" ></span> My delete action';
$actionType = 'delete';
$id = 'mybuttonid' . $n;
$url = $_SERVER['PHP_SELF'] . '?token=' . \newToken() . '#' . $id;
$html = '<span class="fa fa-clone" ></span> My danger action';
$actionType = 'danger';
$id = 'mybuttonid' . $n;
$url = $_SERVER['PHP_SELF'] . '?token=' . \newToken() . '#' . $id;
$label = 'My action label used for accessibility visually for impaired people';
$html = '<span class="fa fa-clone" ></span> My default action';
$actionType = 'default';
$id = 'mybuttonid' . $n;
$url = '#' . $id;
$userRight = 0;
$html = '<span class="fa fa-clone" ></span> My delete action';
$actionType = 'delete';
$id = 'mybuttonid' . $n;
$url = $_SERVER['PHP_SELF'] . '?token=' . \newToken() . '#' . $id;
$html = '<span class="fa fa-clone" ></span> My danger action';
$actionType = 'danger';
$id = 'mybuttonid' . $n;
$url = $_SERVER['PHP_SELF'] . '?token=' . \newToken() . '#' . $id;
$label = 'My action label used for accessibility visually for impaired people';
$html = '<span class="fa fa-clone" ></span> My default action';
$actionType = 'default';
$id = 'mybuttonid' . $n;
$url = '#' . $id;
$userRight = 1;
$params = array('confirm' => []);
$html = '<span class="fa fa-clone" ></span> My delete action';
$actionType = 'delete';
$id = 'mybuttonid' . $n;
$url = $_SERVER['PHP_SELF'] . '?token=' . \newToken() . '#' . $id;
$params = array('confirm' => array('url' => 'your confirm action url', 'title' => 'Your title to display', 'action-btn-label' => 'Your confirm label', 'cancel-btn-label' => 'Your cancel label', 'content' => 'Content to display  with <strong>HTML</strong> compatible <ul><li>test 01</li><li>test 02</li><li>test 03</li></ul>'));
$label = 'My action label used for accessibility visually for impaired people';
$html = '<span class="fa fa-clone" ></span> My default action';
$actionType = 'default';
$id = 'mybuttonid' . $n;
$url = '#' . $id;
$userRight = 0;
$params = array('confirm' => []);
$html = '<span class="fa fa-clone" ></span> My delete action';
$actionType = 'delete';
$id = 'mybuttonid' . $n;
$url = $_SERVER['PHP_SELF'] . '?token=' . \newToken() . '#' . $id;
$params = array('confirm' => array('url' => 'your confirm action url', 'title' => 'Your title to display', 'action-btn-label' => 'Your confirm label', 'cancel-btn-label' => 'Your cancel label', 'content' => 'Content to display  with <strong>HTML</strong> compatible <ul><li>test 01</li><li>test 02</li><li>test 03</li></ul>'));