<?php

// why products?
// Get parameters
$id = \GETPOSTINT('id');
$ref = \GETPOST('ref', 'alpha');
$action = \GETPOST('action', 'aZ09');
$confirm = \GETPOST('confirm', 'alpha');
$cancel = \GETPOST('cancel');
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : 'skillcard';
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
$backtopageforcancel = \GETPOST('backtopageforcancel', 'alpha');
$lineid = \GETPOSTINT('lineid');
// Initialize a technical objects
$object = new \Skill($db);
$extrafields = new \ExtraFields($db);
$search_array_options = $extrafields->getOptionalsFromPost($object->table_element, '', 'search_');
// Initialize array of search criteria
$search_all = \GETPOST("search_all", 'alpha');
$search = array();
// Must be 'include', not 'include_once'.
// Permissions
$permissiontoread = $user->hasRight('hrm', 'all', 'read');
$permissiontoadd = $user->hasRight('hrm', 'all', 'write');
// Used by the include of actions_addupdatedelete.inc.php and actions_lineupdown.inc.php
$permissiontodelete = $user->hasRight('hrm', 'all', 'delete');
$upload_dir = $conf->hrm->multidir_output[isset($object->entity) ? $object->entity : 1] . '/skill';
$MaxNumberSkill = \getDolGlobalInt('HRM_MAXRANK', \Skill::DEFAULT_MAX_RANK_PER_SKILL);
/*
 * Actions
 */
$parameters = array();
$reshook = $hookmanager->executeHooks('doActions', $parameters, $object, $action);
$error = 0;
$backurlforlist = \DOL_URL_ROOT . '/hrm/skill_list.php';
$triggermodname = 'HRM_SKILL_MODIFY';
// Name of trigger action code to execute when we modify record
// action update on Skilldet must be done before real update action in core/actions_addupdatedelete.inc.php
$skilldetArray = \GETPOST("descriptionline", "array:alphanohtml");
// Actions cancel, add, update, update_extras, confirm_validate, confirm_delete, confirm_deleteline, confirm_clone, confirm_close, confirm_setdraft, confirm_reopen
$noback = 1;
// Actions to send emails
$triggersendname = 'HRM_SKILL_SENTBYMAIL';
$autocopy = 'MAIN_MAIL_AUTOCOPY_SKILL_TO';
$trackid = 'skill' . $object->id;
/*
 * View
 */
$form = new \Form($db);
$formfile = new \FormFile($db);
$formproject = new \FormProjets($db);
$title = $langs->trans("Skill");
$help_url = '';
// SKILLDET
$SkilldetRecords = $object->fetchLines();
$res = $object->fetch_optionals();
$head = \skillPrepareHead($object);
$formconfirm = '';
// Call Hook formConfirm
$parameters = array('formConfirm' => $formconfirm, 'lineid' => $lineid);
$reshook = $hookmanager->executeHooks('formConfirm', $parameters, $object, $action);
// Object card
// ------------------------------------------------------------
$linkback = '<a href="' . \DOL_URL_ROOT . '/hrm/skill_list.php?restore_lastsearch_values=1' . (!empty($socid) ? '&socid=' . $socid : '') . '">' . $langs->trans("BackToList") . '</a>';
$morehtmlref = '<div class="refid">';
// for other modules
//dol_include_once('/othermodule/class/otherobject.class.php');
$action = \GETPOST('action', 'aZ09') ? \GETPOST('action', 'aZ09') : 'view';
// The action 'add', 'create', 'edit', 'update', 'view', ...
$massaction = \GETPOST('massaction', 'alpha');
// The bulk action (combo box choice into lists)
$show_files = \GETPOSTINT('show_files');
// Show files area generated by bulk actions ?
$confirm = \GETPOST('confirm', 'alpha');
// Result of a confirmation
$cancel = \GETPOST('cancel', 'alpha');
// We click on a Cancel button
$toselect = \GETPOST('toselect', 'array:int');
// Array of ids of elements selected into a list
$contextpage = \GETPOST('contextpage', 'aZ') ? \GETPOST('contextpage', 'aZ') : 'skilldetlist';
// To manage different context of search
$backtopage = \GETPOST('backtopage', 'alpha');
// Go back to a dedicated page
$optioncss = \GETPOST('optioncss', 'aZ');
// Option for the css output (always '' except when 'print')
$id = \GETPOSTINT('id');
// Load variable for pagination
$limit = 0;
$sortfield = \GETPOST('sortfield', 'aZ09comma');
$sortorder = \GETPOST('sortorder', 'aZ09comma');
$page = \GETPOSTISSET('pageplusone') ? \GETPOSTINT('pageplusone') - 1 : \GETPOSTINT("page");
$offset = $limit * $page;
$pageprev = $page - 1;
$pagenext = $page + 1;
// Initialize a technical objects
$objectline = new \Skilldet($db);
// Initialize array of search criteria
$search_all = \GETPOST('search_all', 'alphanohtml');
$search = array();
// List of fields to search into when doing a "search in all"
$fieldstosearchall = array();
// Definition of array of fields for columns
$arrayfields = array();
$arrayfields = \dol_sort_array($arrayfields, 'position');
// View
$form = new \Form($db);
$now = \dol_now();
$help_url = '';
$title = $langs->transnoentitiesnoconv("Skilldets");
$morejs = array();
$morecss = array();
$nbtotalofrecords = '';
// Build and execute select
// --------------------------------------------------------------------
$sql = 'SELECT ';
$resql = $db->query($sql);
$nbtotalofrecords = $db->num_rows($resql);
$num = $db->num_rows($resql);
$param_fk = "&fk_skill=" . $id . "&fk_user_creat=" . (!empty($user->rowid) ? $user->rowid : 0);
$backtopage = \dol_buildpath('/hrm/skill_card.php', 1) . '?id=' . $id;
$param = "";
$massactionbutton = "";
// Add code for pre mass action (confirmation or email presend form)
$topicmail = "SendSkilldetRef";
$modelmail = "skilldet";
$objecttmp = new \Skilldet($db);
$trackid = 'xxxx' . $object->id;
$moreforfilter = '';
/*$moreforfilter.='<div class="divsearchfield">';
	$moreforfilter.= $langs->trans('MyFilter') . ': <input type="text" name="search_myfield" value="'.dol_escape_htmltag($search_myfield).'">';
	$moreforfilter.= '</div>';*/
$parameters = array();
$reshook = $hookmanager->executeHooks('printFieldPreListTitle', $parameters, $objectline);
$varpage = empty($contextpage) ? $_SERVER["PHP_SELF"] : $contextpage;
// Display all ranks of skill
// --------------------------------------------------------------------
$i = 0;
$totalarray = array();
$parameters = array('arrayfields' => $arrayfields, 'sql' => $sql);
$reshook = $hookmanager->executeHooks('printFieldListFooter', $parameters, $objectline);
// Show links to link elements
$tmparray = $form->showLinkToObjectBlock($object, array(), array('skill'), 1);
$linktoelem = $tmparray['linktoelem'];
$htmltoenteralink = $tmparray['htmltoenteralink'];
$somethingshown = $form->showLinkedObjectBlock($object, $linktoelem);
$MAXEVENT = 10;
$morehtmlcenter = \dolGetButtonTitle($langs->trans('SeeAll'), '', 'fa fa-bars imgforviewmode', \DOL_URL_ROOT . '/hrm/skill_agenda.php?id=' . $object->id);
$formactions = new \FormActions($db);
$somethingshown = $formactions->showactions($object, $object->element . '@' . $object->module, \is_object($object->thirdparty) ? $object->thirdparty->id : 0, 1, '', $MAXEVENT, '', $morehtmlcenter);